export const CONFIG_OPTIONS = 'CONFIG_OPTIONS';
export const PUP_SUB = 'PUP_SUB';
export const NEW_PENDING_ORDER = 'NEW_PENDING_ORDER';
export const NEW_COOKED_ORDER = 'NEW_COOKED_ORDER';
export const NEW_ORDER_UPDATE = 'NEW_ORDER_UPDATE'
